UmbracoTutorial/ViewModels/ProductListingViewModel.cs
using UmbracoTutorial.Models.Records;

namespace UmbracoTutorial.ViewModels;

public class ProductListingViewModel
{
    public List<ProductResponseItem> Products { get; set; } = new();
}

UmbracoTutorial/ViewModels/Umbraco/ProductListingViewModel.cs
using Umbraco.Cms.Core.Models.PublishedContent;
using UmbracoTutorial.Core.UmbracoModels;
namespace UmbracoTutorial.ViewModels.Umbraco;

// We should inherit from PublishedContentWrapped or derived class
public class ProductListingViewModel:Products
{
    public ProductListingViewModel(IPublishedContent content,
        IPublishedValueFallback publishedValueFallback) : base(content,
        publishedValueFallback)
    {
    }

    public List<Product> Products { get; set; } = new();
}

UmbracoTutorial/Controllers/Backoffice/ProductListingController.cs
using Microsoft.AspNetCore.Mvc;
using Umbraco.Cms.Core.Web;
using Umbraco.Cms.Web.BackOffice.Controllers;
using UmbracoTutorial.Core.Services;

namespace UmbracoTutorial.Controllers.Backoffice;

// /umbraco/backoffice/api/ProductListing/GetProducts?number=0
public class ProductListingController:UmbracoAuthorizedApiController
{
    private readonly IProductService _productService;

    public ProductListingController(IProductService productService)
    {
        _productService = productService;
    }

    public IActionResult GetProducts(int number)
    {
        return Ok(_productService.GetUmbracoProducts(number));
    }
}

UmbracoTutorial/ViewComponents/ProductListingViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using UmbracoTutorial.Core.Services;
using UmbracoTutorial.ViewModels;

namespace UmbracoTutorial.ViewComponents;

public class ProductListingViewComponent:ViewComponent
{
    private readonly IProductService _productService;

    public ProductListingViewComponent(IProductService productService)
    {
        _productService = productService;
    }
    
    public IViewComponentResult Invoke(int number)
    {
        var vm = new ProductListingBlockListViewModel()
        {
            Products = _productService.GetUmbracoProducts(number)
        };

        return View("~/Views/Partials/Components/ProductListing/Default.cshtml",vm);
    }
}

UmbracoTutorial/Views/Partials/blocklist/Components/Feature.cshtml
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<Umbraco.Cms.Core.Models.Blocks.BlockListItem>;

@{
    var feature = (Feature)Model.Content;
}

<div class="product-advantage">
    <h4>@feature.FeatureName</h4>
    <h5>@feature.FeatureDetails</h5>
</div>

UmbracoTutorial/Views/Partials/blocklist/Components/productListing.cshtml
@inherits UmbracoViewPage<Umbraco.Cms.Core.Models.Blocks.BlockListItem>
@{
    var content = (ProductListing)Model.Content;
    var settings = (ProductListingSettings)Model.Settings;
}

@await Component.InvokeAsync("ProductListing", settings.NumberOfProducts)

UmbracoTutorial/Views/Partials/blocklist/Components/umbBlockGridDemoImageBlock.cshtml
@inherits UmbracoViewPage<Umbraco.Cms.Core.Models.Blocks.BlockListItem>
@{
    var content = (UmbBlockGridDemoImageBlock)Model.Content;
}
<div class="container-image">
    <img src="@content.Image.Url()" />
</div>

UmbracoTutorial/Views/Partials/blocklist/Components/umbBlockGridDemoRichTextBlock.cshtml
@inherits UmbracoViewPage<Umbraco.Cms.Core.Models.Blocks.BlockListItem>
@{
    var content = (UmbBlockGridDemoRichTextBlock)Model.Content;
    var settings = (RichTextSettings)Model.Settings;
}

<div style="background-color: #@settings.BackgroundColor">
    @content.RichText
</div>